#!/bin/bash

echo Remove artifacts added by requirements.sh to enable a fresh run of requirements.sh
echo -n "Enter YES to continue: "
read continue
if [ "$continue" != 'YES' ]; then
    echo Cleanup not done
else
    rm -rf check-0.15.2 && rm -rf check-0.15.2.tar.gz*
    rm -rf expat-2.6.0 && rm -rf expat-2.6.0.tar.gz*
    rm -rf mbedtls-2.28.7 && rm -rf v2.28.7.tar.gz*
    rm -rf S2OPC
    echo Cleanup completed
fi

